baseURL = "/"
languageCode = "en-us"
title = "Linus Rogge"
theme = "linuscodes"
dateFormat = "Monday, January 2, 2006"

[Params]
   instagram = "https://instagram.com/linuscodes"
   github = "https://github.com/linuscodes"
   mail = "moin@linuscodes.com"
   twitter = "https://twitter.com/linuscodes"
   codepen = "https://codepen.io/linuscodes"

[Permalinks]
   project = "/project/:filename/"
   page = "/:filename/"

[[menu.main]]
   identifier = "projects"
   name = "Projects"
   url = "/projects"
   weight = 1

[[menu.main]]
   identifier = "playground"
   name = "Playground"
   url = "/playground"
   weight = 2

[[menu.main]]
   identifier = "blog"
   name = "Blog"
   url = "https://blog.linuscodes.com"
   weight = 3

[[menu.main]]
   identifier = "uses"
   name = "Uses"
   url = "/uses"
   weight = 4

[[menu.main]]
   identifier = "about"
   name = "About"
   url = "/about"
   weight = 5
